[package]
name = "a"
version = "0.1.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
b = { path = "../b" }